version: '3.9'

services:
        mysql:
                image: mysql
                ports:
                        - ${DATABASE_PORT}:3306
                command: --default-authentication-plugin=mysql_native_password --sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
                restart: always
                volumes:
                        - dbdata:/var/lib/mysql
                environment:
                        - MYSQL_USER=${DATABASE_USERNAME}
                        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
                        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
                        - MYSQL_DATABASE=${DATABASE_NAME}

volumes:
        dbdata:
